this is my first djagno project. It is a blog system.

* django blog V1.0 
** 功能需求
1) blog列表与blog详情显示页面
2) blog支持分类，分类为一级分类,映射基数为N:1
3) blog支持tags,映射基数N:N
4) blog支持评论功能,映射基数1:N
5) 评论支持2级评论，指向自身，映射基数1:N
6) 用户信息模块作为附加考虑
** 阶段划分
*** DONE 基本项目配置
主要内容如下：
基本配置：
1) 数据库参数配置
2) template_dir
3) installed_app
TODO 高级配置:
1) logging配置
2) cache配置
3) 其他配置
*** DONE E-R模型建立，models编写
基本模型一建立，数据库系统临时决定使用sqlite3,可能会有功能上的弱点，后
期可以考虑移植到其他数据库系统
基本模型建模:
1) BLog
2) Comment
3) Tag
4) Category
5) 联系集Blog_Tag
*** DONE admin管理功能
基于django admin的后台功能还是不错的。不过发现model在定义上的一些问题。
需要做修改。另一个问题，发现先创建model init很有必要。这样在后续处理中
就可以方便的调用clearsql 等命令，而不用担心要重建数据。
问题汇总：
1) comments 设计问题.parent_id 与 blog_id冗余，并且没有制定可以为空的
   属性。
2) 应该定义model class 的__unicode__方法一边后续使用方便。
3) 部分SmallInterField应该使用BooleanField代替。
考虑重新优化下建模。

*** TODO 前台功能，views与模板
*** TODO 附加选项
** 项目总结
项目进度基本可以认为失败,失败原因和后续补进如下:
1) model层并不难理解，基本的field和meta配置需要时查文档即可。难点在于
   都整体不够熟悉，会导致考虑欠缺和设计不完善。例外外键是难点，
2) 虽然基本建模不难，但是熟练model的API还是有难度的。
3) Admin层研究不够，做的太粗糙。
4) urlconf配置要强化下，包括模板标签等。
5) django项目现在调试会比较困难，因为输出变量等都未知
